name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Clean
        run: make clean
      - name: Build
        run: git pull --all && git submodule sync; make update; make
